##################################MOTORS######################################
FRONT_LEFT_MOTOR_SPEED_CTRL_PIN = 0
FRONT_LEFT_MOTOR_IN1_PIN = 1
FRONT_LEFT_MOTOR_IN2_PIN = 2

FRONT_RIGHT_MOTOR_SPEED_CTRL_PIN = 5
FRONT_RIGHT_MOTOR_IN1_PIN = 6
FRONT_RIGHT_MOTOR_IN2_PIN = 7

#################################ENCODERS######################################
FRONT_LEFT_ENCODER_CLK_PIN = 3
FRONT_LEFT_ENCODER_DT_PIN = 4
FRONT_LEFT_ENCODER_PULSES_PER_REV = 370

FRONT_RIGHT_ENCODER_CLK_PIN = 8
FRONT_RIGHT_ENCODER_DT_PIN = 9
FRONT_RIGHT_ENCODER_PULSES_PER_REV = 370
